### ISSUE TITLE
Map overlays: One overlay shown in world after closing map; activated overlays not shown after reopening map

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#68]
Build: 40

When all map overlays on Voogle Maps are activated and the map is closed, one building is still colored in the "normal world".
When reopening the map, all overlays are still activated but not shown. Every overlay has to be deactivated and activated again to become visible.

https://user-images.githubusercontent.com/17579552/118718811-fd6dd100-b827-11eb-88ae-8c2ae8a4a805.mp4

**Comment by jhovgaard** [comment]
I can't reproduce, but looking at your mouse hovering the wrong buildings, I think this was fixed earlier when building colliders got fixed.

Can you confirm it works in build 49?

**Comment by Gerwanese** [comment]
The active overlays on the map are now correctly kept in build 49.
The single building however is still troublesome even in a brand new game.
How to reproduce:
1. Walk to the building (corner 9th Ave / 2nd Str)
2. Open Voogle Maps and switch on all overlays
3. Close Voogle Maps
The building is still shown yellow.

New video of build 49:

https://user-images.githubusercontent.com/17579552/120247433-b219e080-c273-11eb-903a-95a9cf1491f0.mp4

**Comment by jhovgaard** [comment]
Fixed in build 68

**Comment by Gerwanese** [comment]
The same is true for Anderson Recruitment, Manhattan Business School, Appliance Store, City Cars. Probably for every two-door building. Might be intended but indeed it looks a bit weird. For me, it would be perfect if doors would always open "forward". If someone leaves the building, door will open to the outside. If someone enters, to the inside.
